scan_filter_chain:
- name: range_cutoff_front_left
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 2.3562
    upper_angle: 3.1416
- name: range_cutoff_front_right
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -3.1416
    upper_angle: -2.3562
- name: laser_median_filter
  type: laser_filters/LaserArrayFilter
  params:
    range_filter_chain:
      - name: median
        type: filters/MultiChannelMedianFilterFloat
        params:
          number_of_observations: 3
          unused: 6 
    intensity_filter_chain:
      - name: median
        type: filters/MultiChannelMedianFilterFloat
        params:
          number_of_observations: 3
          unused: 6
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 5 
    max_angle: 185
    neighbors: 10
    window: 1



